### ISSUE TITLE
What about the Greenbook?

### ISSUE THREAD

**Issue by sahuguet** [MODA-NYC/Agency-Name-Project#1]
You can easily extract agency names from the Greenbook

```
df = pd.read_csv('Greenbook_20240509.csv', usecols=['Agency Name', 'Agency Acronym', 'Agency Website'])
df.drop_duplicates(inplace=True)
df.to_csv('greenbook_agencies.csv', index=False)
```

Is this dataset subsumed by the others?
@npstorey

**Comment by npstorey** [comment]
I updated the Colab notebook to include a section loading and standardizing the Agency name from Greenbook (loading it from the open dataset url) and including a column in the combined dataset. Will include this as a source to compare.
